config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root "homes#show"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "follow" => "following_relationships#create"
      delete "Unfollow" => "following_relationships#destroy"
    end
  end
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resource :dashboard, only: [:show]

end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

  validates :follower_id, uniqueness: { scope: :followed_user_id }
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :image

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts
  
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :followed_user_relationships,
    class_name: "FollowingRelationship",
    foreign_key: :follower_id

  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_user_relationships,
    class_name: "FollowingRelationship",
    foreign_key: :followed_user_id

  has_many :followers, through: :follower_user_relationships

  def follow(user)
    followed_users << user
  end

  def following?(user)
    followed_users.include?(user)
  end

  def unfollow(user)
    followed_users.destroy(user)
  end

  def timeline
    Shout.where(user_id: [id] + followed_user_ids).order(created_at: :desc)
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  before_action :require_login
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = User.find_by(username: params[:id])
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new    
    @shouts = current_user.timeline
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    user = User.find_by(username: params[:id])

    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = User.find_by(username: params[:id])

    current_user.unfollow(user)
    redirect_to current_user 
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login

  def show
    @user = User.new
  end

  def require_login
    if !signed_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
  def create
    photo_shout = PhotoShout.new(photo_shout_params)
    current_user.shouts.create(content: photo_shout)
    

    redirect_to dashboard_path
  end

  private

  def photo_shout_params
    params.
      require(:photo_shout).
      permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def create
    current_user.shouts.create(shout_params)

    redirect_to dashboard_path
  end

  private

  def shout_params
    params.
      require(:shout).
      permit(:body)
  end

end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
  def create
    text_shout = TextShout.new(text_shout_params)
    current_user.shouts.create(content: text_shout)
    

    redirect_to dashboard_path
  end

  private

  def text_shout_params
    params.
      require(:text_shout).
      permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/application/_sign_in.html.erb
<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up.html.erb
<%= form_for user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<div class="timeline">
  <header>
    <h1>Shouts</h1>
  </header>
  <%= render @shouts %>
</div>

<%=form_for @text_shout do |form|%>
  <%= form.text_field :body %>
<%= button_tag icon('bullhorn') %>
   <%end%>

   <%=form_for @photo_shout do |form|%>
  <%= form.file_field :image %>
<%= button_tag icon('bullhorn') %>
   <%end%>

<div class="following">
  Following: <%= render current_user.followed_users %>
 </div>

<div class="followers">
  Followers: <%= render current_user.followers %>
 </div>

app/views/homes/show.html.erb
<div id="home">
  <header>
    <h1>Welcome to Shoutr</h1>
    <p>You can do anything on Shoutr. The only limitation is your imagination!</p>
  </header>

  <div class="home-forms">
    <div class="home-form">
      <%= render "sign_in" %>
    </div>
    <div class="home-form">
      <%= render "sign_up", user: @user %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Shoutr</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body id="<%= [controller_name, action_name].join("-") %>">

  <header class="top-bar">
    <% if signed_in? %>
      <%= link_to "Welcome #{current_user.username }", root_path %>
      <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_session_path %>
      <%= link_to "Sign up", new_user_path %>
    <% end %>
  </header>

  <div id="main-content">
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= div_for(photo_shout) do %>
  <%=image_tag photo_shout.image, width: "200"%>
<%end%>

app/views/shouts/_shout.html.erb
<%= div_for(shout) do %>
  <%=render shout.content%>
  <span style="font-size:8px" ><i>Shouted by <%= shout.user.username %> at about <%= time_ago_in_words(shout.created_at) %> ago</i></span></p>
<%end%>

app/views/text_shouts/_text_shout.html.erb
<%= div_for(text_shout) do %>
  <%=text_shout.body%>
<%end%>

app/views/users/_user.html.erb
<%= link_to user.username, user %>

app/views/users/new.html.erb
<h3>Sign up</h3>

<%= render "sign_up", user: @user %>

app/views/users/show.html.erb
Following: <%=render @user.followed_users %>

<% if current_user == @user%>

<%elsif current_user.following?(@user) %>
  <%= button_to "Unfollow", Unfollow_user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %>
<% else%>
  <%= button_to "Follow", follow_user_path(@user) %>
  <% end %>
<h4><%=@user.username%></h4>
<%= render @shouts%>